version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ts_node 
      PGDATA: /data/posgres
    volumes:
      - ./.docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  adminer:
    image: adminer
    ports:
    - 8080:8080
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
